### ISSUE TITLE
first-load not triggered after last update

### ISSUE THREAD

**Issue by sp4r74cus** [oumoussa98/vue3-infinite-loading#29] opened 2022-07-25 12:13 UTC
Hi 👋🏻 Thanks for your work.

i'm facing an issue since the last update, rolling back to v1.0.6 solved this for me.

**Comment by oumoussa98** [comment] 2022-07-26 13:55
Hi @sp4r74cus, I am unable to reproduce this
If you manage to find a repro case, would help a lot.
However i'm already fixing some issues
Test the new version and let me know if it's fixed on your side

**Comment by oumoussa98** [comment] 2022-07-29 13:54
Reopen this if you still have this issue in the new version

**Closed by oumoussa98** 2022-07-29 13:54 UTC
